language: python
python:
  - "2.7"

# Install dependencies
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-tk
install: 
 - pip install pyserial

# Command to run tests
script:
  - python bin.py -h